# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Set starting index
set -g base-index 1
setw -g pane-base-index 1

# Stop tmux from renaming windows
set-option -g automatic-rename off

# New tmux window in current working dir
bind c new-window -c "#{pane_current_path}"

# Set mouse mode for scrolling
set-option -g mouse on

# Disable auto copy after mouse highlight
unbind-key -T copy-mode-vi MouseDragEnd1Pane

# Color support
set -g default-terminal "tmux-256color"  # use screen-256color if unknown terminal type
set -ga terminal-overrides ",*256col*:Tc"

# vi keybinds for copying
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle  # remember to press space after C-v for it to work
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# Set focus events, helps with neovim autoread
set-option -g focus-events on

# Undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Set fish as default shell/command
set -g default-command fish

# Renumber windows when one is deleted
set-option -g renumber-windows on
